spring:
  application:
    name: formly
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/formly
    username: root
    password: 12345678
server:
  port: 8234

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.sakura.formly.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deletedAt
      logic-delete-value: now()
      logic-not-delete-value: 'null'